version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: snapp-market-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - snapp-market

  redis:
    image: redis:latest
    container_name: snapp-market-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - snapp-market

networks:
  snapp-market:
    driver: bridge

volumes:
  mysql_data: